### PR TITLE
cache: Avoid unlikely zero division.

### PR DESCRIPTION
**Pull request by JoeGruffins**

### CODE REVIEW

**Review by jholdstock — COMMENTED** [review]
I actually considered adding this, but didn't do it because if `bestBlock.PoolSize == 0` probably indicates some kind of underlying issue - eg. misconfigured or misbehaving dcrd. I wanted the panic to occur so it would be logged, and could be investigated.

HOWEVER. At that time, I thought this code was inside of a web request handler, so it would be covered by the panic recovery offered by `recovery.go`. I've just realised that this is not the case, and actually a panic in this code would bring down the whole vspd process.

 Perhaps the best option here is to return an error without updating the cached stats. That will ensure that we are still displaying accurate (if outdated) info on the webpage, and also ensures the unexpected event will show up in the logs.

Thoughts?

**Comment by JoeGruffins** [comment]
I thought it might be something that comes up using the harness sometimes.

Sure, returning an error is maybe ok. It could also be a problem in dcrd that randomly causes this, rather than a problem with vspd.

I'll change this to error if we get 0 for the ticket pool.

**Comment by dnldd** [comment]
Update seems fine but wondering if logging there aren't any tickets to cache and returning wouldn't be the better option here.

**Comment by JoeGruffins** [comment]
> Update seems fine but wondering if logging there aren't any tickets to cache and returning wouldn't be the better option here.

Do you mean not error?

**Comment by dnldd** [comment]
> Do you mean not error?

Yeah.

**Comment by JoeGruffins** [comment]
I thought it was probably fine not to error. It's super unlikely to happen in the first place. I can only imagine something wrong with the rcp return. The chain doesn't move without votes. @jholdstock log and continue or return error?

**Review by dajohi — APPROVED** [review]

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
